import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

let data = "";

export default function Home() {
  const [total, setTotal] = useState(0);
  const [memory, setMemory] = useState(0);

  const allocate = () => {
    data += generateRandomString(10);

    setTotal(data.length / 1000000);
  };

  useEffect(() => {
    if (!(window.performance as any).memory) {
      return;
    }

    setInterval(() => {
      setMemory((window.performance as any).memory.usedJSHeapSize / 1000000);
    }, 1000);
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10">
        <div className="p-2 space-y-1">
          <div className="">Total allocated: {total.toFixed(2)}MB</div>
          <div className="">Memory used: {memory.toFixed(2)}MB</div>
        </div>

        <button
          onClick={allocate}
          className="px-3 py-2 border border-gray-200 rounded-lg text-gray-600 font-medium  bg-gray-50"
        >
          Allocate 100mb
        </button>
      </main>
    </>
  );
}

function generateRandomString(size: number): string {
  size = size * 1000000;

  let result = "";
  const characters =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  const charactersLength = characters.length;
  for (let i = 0; i < size; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
}
